spring:
  application:
    name: Blogly
  datasource:
    url: ${DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

scalar:
  tag-sorter: alpha
  dark-mode: true
  persist-auth: true
  telemetry: false
  authentication:
    preferredSecurityScheme: bearerAuth

app:
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
    name: ${ADMIN_NAME}
