CREATE TABLE post
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   varchar(255) NOT NULL,
    body    text         NOT NULL,
    summary varchar(100)
);

ALTER TABLE post
    ADD CONSTRAINT uc_post_title UNIQUE (title);
