CREATE TABLE article
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   varchar(255) NOT NULL,
    body    text         NOT NULL,
    summary varchar(100)
);

ALTER TABLE article
    ADD CONSTRAINT uc_article_title UNIQUE (title);
